# Generated by Django 4.2.24 on 2026-01-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_remove_firewater_approximate_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewater',
            name='ambulance_notified',
        ),
        migrations.RemoveField(
            model_name='generalincident',
            name='ambulance_notified',
        ),
    ]
