from django.db import models

# Create your models here.
class userdetails(models.Model):
    fullname=models.CharField(max_length=50)
    username=models.CharField(max_length=50)
    userid=models.IntegerField()
    password=models.CharField(max_length=20)
    confirmpassword=models.CharField(max_length=20)

class admindetails(models.Model):
    adminname=models.CharField(max_length=50)
    adminusername=models.CharField(max_length=50)
    adminid=models.IntegerField()
    adminpassword=models.CharField(max_length=20)
    adminconfirmpassword=models.CharField(max_length=20)

class firewater(models.Model):
    userName=models.CharField(max_length=50)
    form_date=models.DateField()
    incident=models.CharField(max_length=50)
    call_number=models.CharField(max_length=50)
    call_received=models.TimeField()
    time_left_station=models.TimeField()
    time_reached_scene=models.TimeField()
    time_returned=models.TimeField()
    occupancy_type=models.CharField(max_length=50)
    construction_type=models.CharField(max_length=50)
    owner_details=models.CharField(max_length=100)
    electrical_chemicals=models.CharField(max_length=100)
    hazardous_materials=models.CharField(max_length=150)
    weather_conditions=models.CharField(max_length=100)
    caller_contact=models.CharField(max_length=60)
    source_of_call=models.CharField(max_length=50)
    nature_incident=models.CharField(max_length=50)
    exact_location=models.CharField(max_length=100)
    owner_occupant=models.CharField(max_length=100)
    premises_occupancy=models.CharField(max_length=50)
    building_details=models.CharField(max_length=100)
    premises_chemicals=models.CharField(max_length=150)
    premises_hazardous=models.CharField(max_length=150)
    deaths_male=models.IntegerField()
    deaths_female=models.IntegerField()
    deaths_adult=models.IntegerField()
    deaths_child=models.IntegerField()
    injuries_male=models.IntegerField()
    injuries_female=models.IntegerField()
    injuries_adult=models.IntegerField()
    injuries_child=models.IntegerField()
    rescued_male=models.IntegerField()
    rescued_female=models.IntegerField()
    rescued_adult=models.IntegerField()
    rescued_child=models.IntegerField()
    fire_personnel_injuries=models.CharField(max_length=150)
    animals_rescued=models.IntegerField()
    animals_lost=models.IntegerField()
    hospital_doctor=models.CharField(max_length=100)
    appliances_crews=models.CharField(max_length=200)
    officer_in_charge=models.CharField(max_length=100)
    equipment_used=models.CharField(max_length=200)
    property_removed=models.CharField(max_length=200)
    property_saved=models.IntegerField()
    property_lost=models.IntegerField()
    building_damage=models.CharField(max_length=150)
    items_destroyed=models.CharField(max_length=200)
    major_loss_cause=models.CharField(max_length=150)   



class generalIncident(models.Model):
    userName=models.CharField(max_length=50)
    form_date=models.DateField()
    incident=models.CharField(max_length=50)
    call_number=models.CharField(max_length=50)
    call_received=models.TimeField()
    time_left_station=models.TimeField()
    time_reached_scene=models.TimeField()
    time_returned=models.TimeField()
    occupancy_type=models.CharField(max_length=50)
    construction_type=models.CharField(max_length=50)
    owner_details=models.CharField(max_length=100)
    electrical_chemicals=models.CharField(max_length=100)
    hazardous_materials=models.CharField(max_length=150)
    weather_conditions=models.CharField(max_length=100)
    caller_contact=models.CharField(max_length=60)
    source_of_call=models.CharField(max_length=50)
    nature_incident=models.CharField(max_length=50)
    exact_location=models.CharField(max_length=100)
    owner_occupant=models.CharField(max_length=100)
    premises_occupancy=models.CharField(max_length=50)
    building_details=models.CharField(max_length=100)
    premises_chemicals=models.CharField(max_length=150)
    premises_hazardous=models.CharField(max_length=150)
    deaths_male=models.IntegerField()
    deaths_female=models.IntegerField()
    deaths_adult=models.IntegerField()
    deaths_child=models.IntegerField()
    injured=models.IntegerField()
    rescued_male=models.IntegerField()
    rescued_female=models.IntegerField()
    rescued_adult=models.IntegerField()
    rescued_child=models.IntegerField()
    fire_personnel_injuries=models.CharField(max_length=150)
    animals_rescued=models.IntegerField()
    animals_lost=models.IntegerField()
    hospital_doctor=models.CharField(max_length=100)
    appliances_crews=models.CharField(max_length=200)
    officer_in_charge=models.CharField(max_length=100)
    equipment_used=models.CharField(max_length=200)
    property_removed=models.CharField(max_length=200)
    property_saved=models.IntegerField()
    property_lost=models.IntegerField()
    building_damage=models.CharField(max_length=150)
    items_destroyed=models.CharField(max_length=200)
    major_loss_cause=models.CharField(max_length=150) 




class AssistanceCall(models.Model):
    userName=models.CharField(max_length=50)
    form_date=models.DateField()
    incident_type=models.CharField(max_length=100)
    call_number=models.CharField(max_length=50)
    call_received=models.TimeField()
    time_left_station=models.TimeField()
    time_reached_scene=models.TimeField()
    time_returned=models.TimeField()
    assistance_details=models.CharField(max_length=200)
    electrical_chemicals=models.CharField(max_length=100)
    hazardous_materials=models.CharField(max_length=150)
    weather_conditions=models.CharField(max_length=100)
    caller_contact=models.CharField(max_length=60)
    source_of_call=models.CharField(max_length=50)
    exact_location=models.CharField(max_length=100)